#Test
database:
  - host: red
    port: 1234
    name: myapp
    user: admin
    password: secret123

api:
  endpoint: https://api.example.com
  timeout: 30
  retries: 3

features:
  debug: true
  cache: false
  logging:
    level: info
    file: app.log
